### ISSUE TITLE
QA: Testing Canada's links with the new prod content

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#195]
**Agile Requirement**
Regression testing on https://www.volvotrucks.ca/en-ca/ and https://www.volvotrucks.ca/fr-ca/ after deploying from production.

**Comment by DanielaPedrochevd** [comment]
@Andrei-Boiangiu please pick this up after today's release you will need a separate branch to perform this regression testing and make sure to update the ticket status :) Thanks!

**Comment by DanielaPedrochevd** [comment]
related to https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/169

**Comment by manuel-vara** [comment]
> @manuel-vara could you provide access for me + other developers to [the Canadian repository](https://github.com/hlxsites/vg-volvotrucks-ca)? Then we can create a new branch to merge the latest redesign changes to.

Done

**Comment by Andrei-Boiangiu** [comment]
regression tests have been done on the following provided URLs:
https://rd-test--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/
https://rd-test--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/


Know issues to mention here:
- Search needs to be removed
- Some 404s due to incorrect content
- (?) Missing translations in header and footer on the French Canadian page (?)
