### ISSUE TITLE
Testing: Volvo ability to upload videos using "My assets" functionality

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#330]

**Comment by ZoeBeykirch** [comment]
After testing "My Assets" as a content editor, I can see the videos in the sidekick, but before last week's Github release, there was an option to copy and paste the video block - and now I no longer see any way to copy/paste the video over from the My Assets in order to apply it to the word doc page (see screenshot) 
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/a287d57b-5c82-4c72-9727-23836700b4ac)
