### ISSUE TITLE
Resource Gallery

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#87]
See https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=6697-2613&mode=dev

Which block is this based on?

### Requirements
- Elements:
  - Heading
  - Tertiary button, toggle
  - Video
    - Thumbnail
    - Play button
    - Title
    - Metadata text
  - Document
    - Link/location
    - Title
    - Metadata text

#### Styling
- On the default (collapsed) state, a maximum of 6 videos and 6 document files will be exposed
  - Both videos and document files are in their own list. If there are 4 videos, the document files remain in place.
- If the video title length exceeds one line, the text will truncate with ellipsis (`text-overflow` to be used)
- Colours change [according to context](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=806-5138&mode=design&t=UXeuvf1juqR4QUJ7-4)

#### Behaviour
- Toggle button
  - “View All” button will reveal all content. On large screens, the component will be displayed as a list view while on tablet and mobile it will be displayed in a form of a carousel
  - “View Less” will revert the component back to the default state
- Tapping a video thumbnail will open a modal, showing the video

**Comment by ZoeBeykirch** [comment]
Here's an example of a similar "More Resources" block with 6+ images/CTAs aligned 3 columns, 2+ rows:

https://www.volvotrucks.us/trucks/vnr-electric/specifications/ 
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/d72ac996-3648-496c-887d-c4b94593bfac)

**Comment by DanielaPedrochevd** [comment]
**Agile Requirement** 

As a business owner I want to be able to display documents and videos in a gallery way so that user's can navigate through the videos and download the documents easily. 

**Description**

Create the Resource Gallery block https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=6697-2613&mode=dev. There's an existing design which can be used as code base https://www.volvotrucks.us/trucks/vnr-electric/specifications/.

**Acceptance Criteria**


1.  There is a new block available with the follwing elements:

- Heading
- Tertiary button, toggle
- Video
- Thumbnail
- Play button
- Title
- Metadata text
- Document
- Link/location
- Title
- Metadata text
- Styling

2. The styling of the block is as follows: 

- On the default (collapsed) state, a maximum of 6 videos and 6 document files will be exposed.
- Both videos and document files are in their own list. If there are 4 videos, the document files remain in place.
- If the video title length exceeds one line, the text will truncate with ellipsis (text-overflow to be used)
- Colours change [according to context](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=806-5138&mode=design&t=UXeuvf1juqR4QUJ7-4).

3. The behaviour of the block is as follows: 

- Toggle button.
- “View All” button will reveal all content. On tablet and mobile, the carousel will be replaced with a list view.
- “View Less” will revert the component back to the default state.
- Tapping a video thumbnail will open a modal, showing the video.

**Comment by DanielaPedrochevd** [comment]
- Check the volvo trucks existing behavior to see if we can reuse the code if it's not to much trouble. https://www.volvotrucks.us/trucks/vnr-electric/specifications/

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 

"On tablet and mobile, the carousel will be replaced with a list view"

I cannot find any carousel in the design nor in specification. If this is not mistake, please clarify where and which carousel to use.

**Comment by ZoeBeykirch** [comment]
@ozzy-krishnan @csulitzer Can you help clarify the above question?

**Comment by ozzy-krishnan** [comment]
@markovukiceviccn @ZoeBeykirch are you referring to a carousel for the resources section? I'm not sure if we have a component for it in the component library, but I have a screenshot of the resources video in a carousel on mobile view :) 
<img width="655" alt="Screenshot 2023-11-09 at 9 40 27 AM" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/147657281/80877062-964a-4fab-bb97-c2e43462e2dd">

**Comment by DanielaPedrochevd** [comment]
@markovukiceviccn As you can see from Ozzy's comment, videos in the mobile and tablet view are displayed in a carousel way. Users should be able to scroll horizontally through the list of videos while on desktop, videos are displayed in rows of 3 in a list view.
