### ISSUE TITLE
Media with tabs

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#89]
https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7920-33325&mode=design&t=1aAVNIr3cgN0nLme-4

**Comment by BeckyMedlin** [comment]
Need more details, please. @DanielaPedrochevd

**Comment by BeckyMedlin** [comment]
@cogniSyb @Gonzalo-CG Need more details, please.

**Comment by DanielaPedrochevd** [comment]
**Agile requirement**
As a Business Owner, I want to be able to display information related to the different exterior variations of a truck so that my clients can learn more from each of them a pick the correct one for them and their needs. 

**Description**
Create a "Media with tabs" block following the [figma design. ](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7920-33325&mode=design&t=pW7NsxteiskjM24D-4)

**Acceptance Criteria**

1. There is a new block available calles "Media with tabs" for content editors to add to any page. 
2. The style and design of this component is as the [figma file](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7920-33325&mode=design&t=pW7NsxteiskjM24D-4) specifies.

**Comment by DanielaPedrochevd** [comment]
- [ ] What changes when the user navigates through the tabs? Just the left image?

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch Please see question above from Daniela and advise. Thank you!

**Comment by ZoeBeykirch** [comment]
Good question.. Posting it on slack and tagging the design agency to get an answer.

**Comment by ZoeBeykirch** [comment]
@DanielaPedrochevd Yes just the left images should change as the user navigates through the tabs
